In [57]:
import numpy as np

In [58]:
# Create random 5x5 array and populate with numbers between 0 and 1
X = np.random.rand(5, 5)

In [59]:
# Calculate mean and standard deviation
mean = X.mean()
std = X.std()

In [60]:
# Calculate Mean
mean_X = X.mean()

In [61]:
# Calculate Standard Deviation
std_X = X.std()

In [65]:
# Normalize array 
X_normalized = (X - mean) / std

# Print original array and normalized array
print("Original Array:\n", X)
print("\nMean of X:", mean_X)
print("Standard Deviation of X:", std_X)
print("\nNormalized Array:\n", X_normalized)

# Save and print saved file name
np.save("X_normalized.npy", X_normalized)
print("\nNormalized array saved as 'X_normalized.npy'")

Original Array:
 [[0.95895433 0.79880155 0.63408688 0.14686358 0.91448791]
 [0.82379238 0.56745226 0.90494344 0.34469005 0.34451736]
 [0.54308778 0.91566379 0.74918788 0.498106   0.90452171]
 [0.15134974 0.11158792 0.81604001 0.61034154 0.43233711]
 [0.14959765 0.53159561 0.65255454 0.59189127 0.02426123]]

Mean of X: 0.5648285400837969
Standard Deviation of X: 0.28300200715135776

Normalized Array:
 [[ 1.39266077  0.82675387  0.24472738 -1.47689752  1.23553672]
 [ 0.91506007  0.00927101  1.20181093 -0.77786902 -0.77847921]
 [-0.07682194  1.23969173  0.65144183 -0.23576703  1.20032072]
 [-1.46104546 -1.60154559  0.88766674  0.16082217 -0.46816429]
 [-1.46723655 -0.11743003  0.30998366  0.09562733 -1.9101183 ]]

Normalized array saved as 'X_normalized.npy'


In [66]:
import numpy as np

# Create 10x10 array of squares of first 100 positive integers
A = np.arange(1, 101)**2
A = A.reshape(10, 10)

# Find elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save result
np.save("div_by_3.npy", div_by_3)

# Print results
print("Array of squares (10x10):\n", A)
print("\nNumbers divisible by 3:\n", div_by_3)
print("\nResult saved as 'div_by_3.npy'")

Array of squares (10x10):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Numbers divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Result saved as 'div_by_3.npy'
